[tool.poetry]
name = "interviews"
version = "0.1.0"
package-mode = false
description = "trying out interview questions"
authors = ["rks"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.13"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
